#ConsoleHandler выводит все сообщения в System.err
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level =ALL
java.util.logging.ConsoleHandler.formatter =java.util.logging.SimpleFormatter
.level=ALL
ru.tet.jetty.basic.level = INFO
org.eclipse.jetty.level = INFO
org.eclipse.jetty.server.Server.level = FINE