<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>ru.tetsu</groupId>
		<artifactId>tet-demos</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>td10-libs</artifactId>

	<properties>
		<maven.compiler.source>20</maven.compiler.source>
		<maven.compiler.target>20</maven.compiler.target>
	</properties>

	<dependencies>

		<dependency>
			<groupId>ru.tetsu</groupId>
			<artifactId>td-aux</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>ru.tetsu</groupId>
			<artifactId>tet-utils</artifactId>
			<version>${project.version}</version>
		</dependency>


		<!-- misc -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>

		<dependency>
			<groupId>org.reflections</groupId>
			<artifactId>reflections</artifactId>
		</dependency>

		<dependency>
			<groupId>com.javax0.sourcebuddy</groupId>
			<artifactId>SourceBuddy</artifactId>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>


		<!-- libs to test -->
		<dependency>
			<groupId>org.ehcache</groupId>
			<artifactId>ehcache</artifactId>
			<version>3.4.0</version>
		</dependency>

		<!-- необходим для ehcache (если использовать xml-конфигурацию) -->
		<!--
			
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>2.3.1</version>
		</dependency>
		-->


	</dependencies>

</project>